### ISSUE TITLE
example.py folder giving me a strange error- HELP!!!

### ISSUE THREAD

**Issue by shellyalv** [johnyf/nx2tikz#3]
I just installed Instabot with Python 3 and everything has loaded correctly. I am not a developer, nor do I understand code much, but I have followed instructions to the "T," and now have an issue. I am at the last step where I want to edit the example.py folder, so I types sudo nano example.py, but this messages comes up:

The example.py is deprecated. Please use the declarative mode with YAML settings
Please refer to Github README + (instabot -h) + Blog section for further information

I am not sure what this means, but there is no example file with settings to edit. Please help!!!

**Comment by johnyf** [comment]
This issue does not appear relevant to this repository: this repository is for the Python package `nx2tikz`, not for "instabot". The reported message is from some program other than `nx2tikz`. Also, even in that other program's contents:
- `example.py` is probably a text file (containing [Python](https://en.wikipedia.org/wiki/Python_(programming_language)) code), not a folder
- typing `sudo nano example.py` would edit the file, not run Python and print a message
- typing `python example.py` would run the script `example.py` using Python, which is probably what happened and printed the reported message, and
- typing [`sudo`](https://en.wikipedia.org/wiki/Sudo) in front of `nano example.py` would better be avoided, because it would probably change the security attributes of the file in an unintended way.

I would suggest finding the repository that corresponds to the software project that the question is about, and reading the README of that repository, as noted in the reported message.

Regarding the `nx2tikz` package, there is an example [Python script `examples/example.py`](https://github.com/johnyf/nx2tikz/blob/master/examples/example.py) that can be run to create an example graph.
